/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ReadApp {

    public static void main(String[] args) {
        SpringApplication.run(ReadApp.class, args);
    }
}
